fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.1
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile.git
    mysql: 
      repo: git://github.com/puppetlabs/puppetlabs-mysql.git
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
    apache:
      repo: git://github.com/puppetlabs/puppetlabs-apache.git
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: 1.1.1
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 0.0.6
    sudo:
      repo: git://github.com/saz/puppet-sudo.git
      ref: v3.0.1
    gpg_key:
      repo: git://github.com/treydock/puppet-gpg_key.git
      ref: 0.0.3
    cron: git://github.com/treydock/puppet-cron.git
  symlinks:
    osg: "#{source_dir}"
