fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    epel: git://github.com/stahnma/puppet-module-epel.git
    mysql: git://github.com/puppetlabs/puppetlabs-mysql.git
    firewall: git://github.com/puppetlabs/puppetlabs-firewall.git
    create_resources: git://github.com/puppetlabs/puppetlabs-create_resources.git
    cron: git://github.com/treydock/puppet-cron.git
  symlinks:
    osg: "#{source_dir}"
