fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.1
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile.git
    mysql: 
      repo: git://github.com/puppetlabs/puppetlabs-mysql.git
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
    apache:
      repo: git://github.com/puppetlabs/puppetlabs-apache.git
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: 2.2.1
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 1.0.0
    sudo:
      repo: git://github.com/saz/puppet-sudo.git
      ref: v3.1.0
    logrotate:
      repo: https://github.com/yo61/puppet-logrotate
  symlinks:
    osg: "#{source_dir}"
