fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    epel: git://github.com/stahnma/puppet-module-epel.git
    mysql: 
      repo: git://github.com/puppetlabs/puppetlabs-mysql.git
      ref: 0.9.0
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 0.4.0
    create_resources: git://github.com/puppetlabs/puppetlabs-create_resources.git
    cron: git://github.com/treydock/puppet-cron.git
    sudo:
      repo: git://github.com/saz/puppet-sudo.git
      ref: v2.2.0
    apache:
      repo: git://github.com/puppetlabs/puppetlabs-apache.git
      ref: 0.9.0
    concat: git://github.com/ripienaar/puppet-concat.git
    gpg_key: git://github.com/treydock/puppet-gpg_key.git
  symlinks:
    osg: "#{source_dir}"
