---
default_set: 'scientific-64-x64'
sets:
  'centos-64-x64':
    nodes:
      'main.vm.osg':
        prefab: 'centos-64-x64'
  'centos-59-x64':
    nodes:
      'main.vm.osg':
        prefab: 'centos-59-x64'
  'scientific-64-x64':
    nodes:
      'main.vm.osg':
        prefab: 'scientific-64-x64'